### ISSUE TITLE
All elements in view port

### ISSUE THREAD

**Issue by MarinescuEvghenii** [roderickhsiao/react-in-viewport#10]
It will be great to know all elements which are in view port. Is that possible?

**Comment by roderickhsiao** [comment]
What kind of use case do you have in mind?

Technically we could pass the element as payload for `onEnterViewport` and `onLeaveViewport` 
https://github.com/roderickhsiao/react-in-viewport/blob/master/src/index.js#L115

but you will need to have your own function/class to manage the map and pass the function into each individual `react-aspect-ratio` HOC.

For instance

```js
class ViewportManager {
  constructor() {
    this.subscriptions = new Set();
  }

  onEnterViewport(node) {
    if (!subscriptions.has(node)) {
      subscriptions.add(node); 
    }
  }
  
  getAllElementsInViewport = () => this.subscriptions;
}
```

**Comment by MarinescuEvghenii** [comment]
Thanks @roderickhsiao. That exactly what I did.

**Comment by roderickhsiao** [comment]
Thanks @MarinescuEvghenii yes, it probably doesn't make sense to have that logic in the library, but if lots of people is requesting the feature, we could probably add another wrapper exporting individually to minimize the bundle size required for most of the user
