### ISSUE TITLE
How to pass down props to a functional component in typescript through the HOC?

### ISSUE THREAD

**Issue by akshg05** [roderickhsiao/react-in-viewport#101]
I have a functional component Body which takes in props from its parent component Parent.
I am unable to pass down the props by using 
`const ViewportBlock = handleViewport(Body)`
as my rendering fails as no props are passed.
If I do something like
`const ViewportBlock = handleViewport(() => Body(props))`
then I am unable to attach the ref needed and hence the Intersection api does not work.
Can you please guide me how to use this here?
I am new to React so any help will be appreciated.

**Comment by roderickhsiao** [comment]
You should be able to do it.

```js
const const ViewportBlock = handleViewport(Body);

const Parent = (props) => {
  return (<ViewportBlock {...props} />;
}
```

as `handleViewport` will pass down all props https://github.com/roderickhsiao/react-in-viewport/blob/main/src/lib/handleViewport.js#L51
