### ISSUE TITLE
New issue From the last version

### ISSUE THREAD

**Issue by jfnault-seedbox** [roderickhsiao/react-in-viewport#103]
Im still looking at it, the error is:
Uncaught Error: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead.

we are on react 17.

I will for now force previous version

**Comment by roderickhsiao** [comment]
@jfnault-seedbox you still see the same issue?

**Comment by jfnault-seedbox** [comment]
> @jfnault-seedbox you still see the same issue?

I will look at it today and give you updates thank

**Comment by jfnault-seedbox** [comment]
> @jfnault-seedbox you still see the same issue?

I still have the issue

**Comment by roderickhsiao** [comment]
@jfnault-seedbox 

Will be helpful if you can provide some more information

1. which version you are using
2. How you are using the library (HOC or Hook)
3. Minimal rendering logic of your component.
4. Minimal reproducible example will be a huge help!
Thanks
