### ISSUE TITLE
type error with `useInViewport`

### ISSUE THREAD

**Issue by andyGallagher** [roderickhsiao/react-in-viewport#108]
Receiving a type error for the ref value passed to the `useInViewport` hook.

For the following code:
```

const Section = () => {
    const ref = useRef<HTMLElement>(null);
    const { enterCount, leaveCount } = useInViewport(ref);
  
    return (
      <section ref={ref}>
        <div>
          <h1>Hello</h1>
          <p>{`Enter viewport: ${enterCount} times`}</p>
          <p>{`Leave viewport: ${leaveCount} times`}</p>
        </div>
      </section>
    );
  };
```

The following type error appears:
```
Argument of type 'RefObject<HTMLElement>' is not assignable to parameter of type 'MutableRefObject<HTMLElement>'.
  Types of property 'current' are incompatible.
    Type 'HTMLElement | null' is not assignable to type 'HTMLElement'.
      Type 'null' is not assignable to type 'HTMLElement'.ts(2345)
```

Noticed that there was [recently an update to this](https://github.com/roderickhsiao/react-in-viewport/pull/107), not sure if this is working out as intended.  It looks like [there are truthy checks for any references to this target](https://github.com/roderickhsiao/react-in-viewport/blob/2314fa6248e74a5d3a5714b743a63f2fe1e647db/src/lib/useInViewport.tsx#L27-L44), so setting the useInViewport function signature to the following — with target being `target: React.MutableRefObject<HTMLElement | null>` — might be an option here:
```
(target: React.MutableRefObject<HTMLElement | null>, options?: Options, config?: Config, props?: Props)
```

**Comment by roderickhsiao** [comment]
It seems like the dist published are missing updated type definition https://unpkg.com/browse/react-in-viewport@1.0.0-alpha.27/dist/types/lib/useInViewport.d.ts

**Comment by roderickhsiao** [comment]
re-publish `1.0.0-alpha.28` 

https://unpkg.com/browse/react-in-viewport@1.0.0-alpha.28/dist/types/lib/useInViewport.d.ts
