### ISSUE TITLE
Latest breaks Internet Explorer 11

### ISSUE THREAD

**Issue by andrewjsauer** [roderickhsiao/react-in-viewport#111]
Using HOC option, I pulled latest `v1.0.0-alpha.28` and tested on Internet Explorer 11 with the `intersection-observer` polyfill installed. Error thrown until I downgraded to `v1.0.0-alpha.20` where things were working as expected.

Unfortunately, IE11 does not produce the most helpful errors, `SCRIPT16389: Unspecified error` is what I saw in the console.

**Comment by roderickhsiao** [comment]
Most likely is compiling issue that some js syntax is not supported, I didn't see any syntax (arrow function/ES6 class) https://unpkg.com/browse/react-in-viewport@1.0.0-alpha.28/dist/lib/

Not really sure what's causing the issue, do you have a minimal working example to share?

Thanks
