### ISSUE TITLE
The use of useInViewport affects the scrolling behaviour

### ISSUE THREAD

**Issue by mnieber** [roderickhsiao/react-in-viewport#112]
I notice that my page has a different scrolling behaviour when I use useInViewport: the scrolling stops once the component comes into view. I was expecting the hook to only report on components entering and leaving, but it seems that it also affects the scrolling itself (it breaks the fluency of the scrolling).

PS I tested this by only adding or removing  the call to useInViewport(), without using the information returned by this hook.

**Comment by roderickhsiao** [comment]
Thanks for reporting,

is this happens to you for all devices/browsers?

Do you have a minimal reproducible example?

I'm using https://roderickhsiao.github.io/react-in-viewport/?path=/story/enter-callback--class-base-component and checking the frame rate on scroll, I didn't see obvious drops.

**Comment by mnieber** [comment]
Hi Roderick, I think we can close this issue because afaict it's directly related to the IntersectionObserver (and has nothing to do with your code). I mean, I get the same jerky scrolling if I add an IntersectionObserver to my component.  But I see that in your code indeed it works fine (it would be nice to know what makes the difference, if I find out I will post it here).

**Comment by roderickhsiao** [comment]
Thanks! Yeah it will be good to know and anything we can feedback to the browser vendor (or via different intersection observer configurations for best practices) 

Thanks for reporting again, keep me updated :)
