### ISSUE TITLE
IE syntax issue

### ISSUE THREAD

**Issue by Emiliano-Bucci** [roderickhsiao/react-in-viewport#22]
Hi! I'm trying to use this lib with Next.Js and testing it in IE (v11), but in the console i'm getting this a syntax error in this line: 

`const forwardedRefComponent = (0, _react.forwardRef)((props, ref) => _react.default.createElement(TargetComponent, _extends({}, props, {{forwardedRef: ref}));`

Of course it doesn't work, and i'm guessing that can be because of this: any idea? :/ Thanks! :)

**Comment by roderickhsiao** [comment]
Which version are you currently using? the `1.0.0 alpha` version is not yet ready (still work in progress), you could try version 0.x (0.0.37)

Also we have two build targeting different syntax
`dist` and `dist/es` 

You could either include `react-in-viewport` in your build (most people exclude node_modules) or you can just alias `react-in-viewport/dist/es` to `react-in-viewport/dist` assuming you are using webpack :)

Let me know if you are still having issue

**Comment by Emiliano-Bucci** [comment]
Hi! Thanks for the quick answer :) Currently i'm using `v0.0.37` but still getting the error. Could you please, in short, explain how could i alias the packages? Thank you very much for your time :)

**Comment by roderickhsiao** [comment]
for alias

https://webpack.js.org/configuration/resolve/

```js
module.exports = {
  //...
  resolve: {
    alias: {
     'react-in-viewport/es/dist': 'react-in-viewport/dist`
    }
  }
};
```

**Comment by Emiliano-Bucci** [comment]
Thanks! :)

**Comment by roderickhsiao** [comment]
Thanks for using the library, feel free to reach out if you have further questions
