### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by francisrod01** [roderickhsiao/react-in-viewport#26]
The README.md examples don't work

![image](https://user-images.githubusercontent.com/4691768/56842408-2c90fe80-686b-11e9-91b8-9ea514584a1b.png)

## Envs

- `react`: `^16.8.6`
- `react-dom`: `^16.8.6`
- `react-in-viewport`: `^1.0.0-alpha.3`

Code reprodution on `Codesandbox`:

https://codesandbox.io/s/x35r6z7lxq

**Comment by roderickhsiao** [comment]
@francisrod01 thanks for reporting, Just update the readme, you will need to attach `ref` from `innerRef` props.

https://github.com/roderickhsiao/react-in-viewport/blob/0.x/README.md#example-for-enterleave-counts

Also `1.0.0-alpha` still work in progress, will suggest to use `0.0.37` version

update code here https://codesandbox.io/s/wo6qm5l64k

**Comment by francisrod01** [comment]
It works now! Thanks @roderickhsiao!!

**Comment by roderickhsiao** [comment]
Thanks for reporting, also v1 might be ready soon just fyi :)
