### ISSUE TITLE
How can I disconnect on enter?

### ISSUE THREAD

**Issue by ghost** [roderickhsiao/react-in-viewport#52]
There is an example with a manual usage of IntersectionObserver
```
const imageObserver = new IntersectionObserver((entries, imgObserver) => {
  entries.forEach((entry) => {
   if (entry.isIntersecting) { // important string
      const lazyImage = entry.target
      console.log("lazy loading ", lazyImage)
      lazyImage.src = lazyImage.dataset.src
      lazyImage.classList.remove("lzy_img");
      imgObserver.unobserve(lazyImage); // important string
    }
  })
});
const arr = document.querySelectorAll('img.lzy_img')
arr.forEach((v) => {
  imageObserver.observe(v);
})
```

In your library how can I make my component unobserve?

**Comment by roderickhsiao** [comment]
@theboss9976 if you want to disconnect the intersection observer after entering viewport, you could pass `disconnectOnLeave` in the config then the library will unobserve after `onEnterr`

https://github.com/roderickhsiao/react-in-viewport#supported-config
