### ISSUE TITLE
Add rootMargin &/or threshold?

### ISSUE THREAD

**Issue by tomByrer** [roderickhsiao/react-in-viewport#56]
Problem: Trigger box is sometimes too big or too small
Platform: Firefox on Win10
Manual tests:
1.  [Class based](https://roderickhsiao.github.io/react-in-viewport/?path=/story/enter-and-leave-callback--class-based-component): Triggers when 1px is matching or goes into viewport.  Kinda expected behavior IMHO, but may be a problem in some scenarios.
2. [Function based link ](https://roderickhsiao.github.io/react-in-viewport/?path=/story/enter-and-leave-callback--functional-component)example: triggers when the space between the link & the "onEnterViewport and onLeaveViewport callback" line enters & leaves the viewport; visually too early IMHO.

This report is not really a 'bug report'/suggestion per se, but as a FYI-to-warning about expectations how this component, can cause incorrect behavior/data.  Either way is fine for lazy-load (or even desirable), but bad for say [trackers](https://github.com/yahoo/react-i13n).  Tracker-triggers will be inaccurate due to triggers of the Intersection Observer happening before the user actually sees the tracked item, thus may have a % of false-positives.

If you think the extra code complexity is worth more fine-grained accuracy (eg to improve trackers), then there are [options](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#Intersection_observer_options).

**Comment by roderickhsiao** [comment]
@tomByrer thanks for the details! 
You can pass the intersection observer options in the second param when wrapping with the HOC.

https://github.com/roderickhsiao/react-in-viewport#usages

```js
handleViewport(Component, Options, Config)
```
