### ISSUE TITLE
return after disconnecting

### ISSUE THREAD

**Issue by sibasishm** [roderickhsiao/react-in-viewport#65]
https://github.com/roderickhsiao/react-in-viewport/blob/91cff5730f5aa5bbcdb46a3a60ddbcd954ec13bd/src/lib/useInViewport.js#L58

Shouldn't there be a `return;` after the observer is disconnected?

**Comment by roderickhsiao** [comment]
```js
leaveCountRef.current += 1;
inViewportRef.current = isInViewport;
forceUpdate(isInViewport);
```
Still required to update the component at that specific exit for viewport.

**Comment by sibasishm** [comment]
Makes sense but my use case didn't require the update. Thanks for replying.
