### ISSUE TITLE
Missing typings file

### ISSUE THREAD

**Issue by agilatakishiyev** [roderickhsiao/react-in-viewport#70]
Hi this is a great component, but yet i had a problem when using this in a react typescript project.
When i try to import something from it i get the following error
Could not find a declaration file for module 'react-in-viewport'. '/Users/aeatakishiyev/Documents/GitHub/ui-client/node_modules/react-in-viewport/dist/index.js'
i surpassed it by using require statement, but it would be great if you add a declaration module for this library

**Comment by roderickhsiao** [comment]
Thanks for recommendation, I dont personally use type script in my project, but will be very happy to accept PR :) cheers

**Comment by agilatakishiyev** [comment]
ok then) i will try to open a pr for it

**Comment by popzelife** [comment]
If you need help @agilatakishiyev here is a type declaration I use on my own. It's a good start

```typescript
declare module 'react-in-viewport' {
  export type ViewportConfig = {
    disconnectOnLeave?: boolean
  }

  export function handleViewport<P>(
    block: ReactNode,
    options?: IntersectionObserver,
    config?: ViewportConfig
  ): React.ComponentType<
    P & {
      onEnterViewport?: VoidFunction
      onLeaveViewport?: VoidFunction
    }
  >

  export type PropsInViewport = {
    inViewport: boolean
    enterCount: number
    leaveCount: number
    forwardedRef?: React.MutableRefObject
    onEnterViewport?: VoidFunction
    onLeaveViewport?: VoidFunction
  }

  export default handleViewport
}

```

**Comment by lencse** [comment]
Hi!

I created a PR to add type definitons: #87 
I tried not to clutter the source file too much. @popzelife thanks for your comment, it was helpful to start.
