### ISSUE TITLE
Remove finddomnode from the useInViewport hook

### ISSUE THREAD

**Issue by Olierook** [roderickhsiao/react-in-viewport#73]
You can easily get rid of the about to be deprecated finddomnode with react hooks:
[example](https://reactjs.org/docs/hooks-faq.html#how-can-i-measure-a-dom-node)

**Comment by PCOffline** [comment]
Hey, any updates on this?

**Comment by PCOffline** [comment]
Bumping this once again :)

**Comment by roderickhsiao** [comment]
Hi @PCOffline 

Some potential approaches

### `useInViewport` hook
1. If we change the interface assuming item passing down to hook is Ref with HTML element, then we don't need to use `findDOMNode`, client will need to handle finding the node either attaching React ref or using `useRef` and stores them HTML DOM Node (using Javascript API), this part is relatively easy

### HOC
1. HOC case is a bit complicated as the interface will easily create props drilling by passing `ref` to each level of the child (sometimes the component is third-party library), we could say its a breaking change and doesn't care about it but this is a pretty standard use case for people using the library
2. We allow passing CSS selectors like id/class name and we grab the DOM node from the HOC and pass it down to the `useInViewport` hook. It's basically implementing `findDOMNode` using Javascript API and avoiding props drilling.
The downside will be this is not really a React way to handle it and DOM changes won't broadcast for the update, so we might need to handle lifecycle properly with caution.

Open for suggestions and PRs :) 

The current PR has some issues and I don't think it's a comprehensive approach.
